name: Pack Docker Images

on:
  workflow_dispatch: # 支持手动点击按钮触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Images
        run: |
          docker pull ghcr.io/home-assistant/home-assistant:stable
          docker pull ghcr.io/rhasspy/wyoming-sherpa-onnx:latest
          docker pull rhasspy/wyoming-faster-whisper:latest
          
          docker save ghcr.io/home-assistant/home-assistant:stable ghcr.io/rhasspy/wyoming-sherpa-onnx:latest rhasspy/wyoming-faster-whisper:latest -o cinema-images.tar
          
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: cinema-images.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
